FROM golang:1.8

ARG APP=github.com/deepglint/hela

WORKDIR /go/src
COPY . $APP
RUN go-wrapper download $APP
RUN go-wrapper install $APP

WORKDIR /go/bin
ENV BACKEND_API UNSET
ENV KAFKA_BROKE_EVENT UNSET
ENV KAFKA_BROKE_CAPTURE  UNSET
ENV KAFKA_PARTITION_EVENT  0
ENV KAFKA_PARTITION_CAPTURE 0
ENV KAFKA_OFFSET_EVENT  -1
ENV KAFKA_OFFSET_CAPTURE -1
ENV KAFKA_TOPIC_EVENT  warned-push
ENV KAFKA_TOPIC_CAPTURE captured-push
ENV HTTP_PORT :8082
ENV KAFKA_TOPIC_SENDER facedeplin
ENV KAFKA_BROKE_SENDER UNSET
ENV THRESHOLD 0.85
ENV DB_ENGINE postgres
ENV DB_CONN UNSET
EXPOSE 8082


CMD ./hela
